### PR TITLE
only use `extends` when required, added parameter types.

### PR DESCRIPTION
**Pull request by nalbion**
Resolution for #3 and #4.

### CODE REVIEW

**Comment by nalbion** [comment]
I've used this to process all of the Polymer & Google elements: https://github.com/nalbion/polymer-elements-typings

**Comment by bsorrentino** [comment]
Hi

Thanks for contributions 

I'll check and merge asap

**Comment by bsorrentino** [comment]
I've seen your project [polymer-elements-typings](https://github.com/nalbion/polymer-elements-typings)  but your in your pull request seems the the `<reference path=` into generated element create a folder prefix not aligned with pattern `<element prefix>-elements` but only `<element prefix>` (ex. `/// <reference path="../paper/PaperButtonBehavior.d.ts"/>` instead of `/// <reference path="../paper-elements/PaperButtonBehavior.d.ts"/>`. Moreover the generated element should be put (automatically) in the subfolder following the above pattern.

I'm working on ... and will add a new option to enable/disable such feature

**Comment by nalbion** [comment]
Yes, I'm going to change the directory names, removing "-elements"

**Pull request merged**
